on:
  workflow_dispatch

jobs:
  job-one:
    runs-on: ubuntu-latest
    steps:
    - name: show a warning
      run: |
        deprecated=true
          if [[ deprecated ]]; then
            echo "::warning::Debrecated function found"
          fi
    - name: assigne API Key
      run: echo "API_KEY=Pass123" >> $GITHUB_ENV
    - name: use API Key
      run: echo "API Key is $API_KEY"
