on:
  workflow_dispatch

jobs:
  job-one:
    runs-on: ubuntu-latest
    steps:
    - run: |
        deprecated=true
          if [[ deprecated ]]; then
            echo "::warning::Debrecated function found"
          fi
