on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Cohhose an environment"
        required: true
        default: "Testing"
        type: choice
        options:
          - Production
          - Testing
jobs:
  AyHaga:
    runs-on: ubuntu-latest
    steps:
      - name: Run Ayhaga
        run: echo "Ay 7aga 3lashan el manual workflow"
      
