name: Multi Events
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
jobs:
  Hello-World:
    runs-on: ubuntu-latest
    steps:
      - name : "Print Basic Information"
        run: | 
          echo "REF: $HITHUB_REF"
          echo "Job ID: $GITHUB_JOB"
