name: WorkFlow One
on:
  push:
    branches:
      - main
jobs:
  Build_the_website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          
      - name: Checkout the Repo
        uses: actions/checkout@4.2.2
        
      - name: Check Node Version
        run: node --version

      - name: Check npm version
        run: npm --version

      - name: Install dependances 
        run: npm ci

      - name: Build the website
        run: npm run build
        
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: build/
          
  Testing_the_website:
    needs: Build_the_website
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          
      - name: Test t=file existance
        run: test -f build/index.html
  
  Unit-Testing:
    needs: Build_the_website
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          
      - name: Install dependances
        run: npm ci

      - name: Runs unit testing
        run: npm test
